"use client";
import {useEffect,useState} from 'react';
type Case={id:string;email:string;role:string;reason:string;status:string;approvals:number;ready_at:string|null};
export function RecoveryReviews(){
 const [cases,setCases]=useState<Case[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/platform-admin/recovery');const b=await r.json();if(!r.ok)throw Error(b.error);setCases(b);}useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 return <section className="stack"><h2>Assisted account recovery</h2><p>Verify identity through the documented recovery procedure. Record the verification reference, not raw identity documents. Two different reviewers are required; staff accounts require two super-admins. Approval starts a 24-hour security delay.</p><p role="status">{message}</p>{!cases.length&&<p>No active cases.</p>}{cases.map(c=><article className="panel panel-body stack" key={c.id}><h3 style={{overflowWrap:'anywhere'}}>{c.email}</h3><p>{c.role} · {c.status} · {c.approvals} approvals</p><p>{c.reason}</p>{c.ready_at&&<p>Eligible after {new Date(c.ready_at).toLocaleString()}</p>}{c.status==='requested'&&<form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const form=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/platform-admin/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,caseId:c.id,identityVerified:form.identityVerified==='on'})});const b=await r.json();if(!r.ok)throw Error(b.error);setMessage('Review recorded.');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>
 <label className="field">Decision<select name="decision"><option value="approve">Approve verified identity</option><option value="reject">Reject recovery request</option></select></label><label className="field">Verification evidence reference and reason<textarea name="evidenceNote" required minLength={30} maxLength={2000}/></label><label><input type="checkbox" name="identityVerified" required/> I completed the identity review and recorded its outcome.</label><label className="field">Your password<input name="password" type="password" required autoComplete="current-password"/></label><label className="field">Fresh second-factor code<input name="code" required autoComplete="one-time-code" maxLength={32}/></label><button className="button" disabled={busy}>Record decision</button></form>}</article>)}</section>;
}
