CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, email text UNIQUE NOT NULL, password text NOT NULL, role text NOT NULL DEFAULT 'owner', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(token text PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, expires timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS sites(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid REFERENCES users(id), name text NOT NULL, slug text UNIQUE NOT NULL, category text NOT NULL CHECK(category IN ('corporate','commerce')), tier text NOT NULL CHECK(tier IN ('basic','growth','advanced')), status text DEFAULT 'draft', subscription text DEFAULT 'pending', data jsonb NOT NULL, published jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE, kind text NOT NULL, data jsonb NOT NULL, created_at timestamptz DEFAULT now());
CREATE INDEX IF NOT EXISTS records_site_kind ON records(site_id,kind);
CREATE UNIQUE INDEX IF NOT EXISTS records_slug ON records(site_id,kind,(data->>'slug')) WHERE kind IN ('pages','articles','products');
CREATE TABLE IF NOT EXISTS media(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), site_id uuid REFERENCES sites(id), bytes bytea NOT NULL, alt text NOT NULL DEFAULT '', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS plans(id text PRIMARY KEY, category text NOT NULL, tier text NOT NULL, monthly integer, annual integer, currency text DEFAULT 'NGN');
INSERT INTO plans(id,category,tier) SELECT c||'-'||t,c,t FROM unnest(ARRAY['corporate','commerce']) c CROSS JOIN unnest(ARRAY['basic','growth','advanced']) t ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS billing(reference text PRIMARY KEY, site_id uuid REFERENCES sites(id), amount integer NOT NULL, currency text NOT NULL DEFAULT 'NGN', status text DEFAULT 'pending', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS audit(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor text NOT NULL, action text NOT NULL, target text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS rate_limits(key text PRIMARY KEY, count integer NOT NULL, reset_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS domains(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),site_id uuid REFERENCES sites(id),hostname text UNIQUE NOT NULL,token text NOT NULL,verified_at timestamptz,active boolean DEFAULT false);
ALTER TABLE sites ADD COLUMN IF NOT EXISTS paid_until timestamptz;
ALTER TABLE billing ADD COLUMN IF NOT EXISTS interval text DEFAULT 'monthly';
ALTER TABLE plans ADD COLUMN IF NOT EXISTS entitlements jsonb;
CREATE TABLE IF NOT EXISTS merchant_accounts(site_id uuid PRIMARY KEY REFERENCES sites(id),secret text NOT NULL,verified boolean DEFAULT false,delivery integer DEFAULT 0);
CREATE TABLE IF NOT EXISTS orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),site_id uuid REFERENCES sites(id),reference text UNIQUE NOT NULL,customer jsonb NOT NULL,items jsonb NOT NULL,amount integer NOT NULL,currency text DEFAULT 'NGN',payment_status text DEFAULT 'pending',fulfilment_status text DEFAULT 'unfulfilled',created_at timestamptz DEFAULT now());
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified boolean DEFAULT false;
CREATE TABLE IF NOT EXISTS auth_tokens(token text PRIMARY KEY,user_id uuid REFERENCES users(id) ON DELETE CASCADE,purpose text NOT NULL,expires timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS email_outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),recipient text NOT NULL,subject text NOT NULL,body text NOT NULL,sent_at timestamptz,created_at timestamptz DEFAULT now());
